version: "3.8"

services:

  postgres:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  web-server:
    restart: always
    container_name: web-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: web-server
    ports:
      - 4557:4557
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
    command: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 4557"]
    profiles:
      - server

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - 5050:80

volumes:
  pgdata:
