"""Create schema and test data

Revision ID: f4f89c94c677
Revises: 
Create Date: 2024-04-16 20:36:36.644225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

from app.models import Customer, Event

bind = op.get_bind()
session = orm.Session(bind=bind)

# revision identifiers, used by Alembic.
revision: str = 'f4f89c94c677'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    event_one = Event(seats=300, name="concerto")
    event_two = Event(seats=300, name="convegno")
    event_three = Event(seats=300, name="partita")
    session.add_all([event_one, event_two, event_three])
    session.commit()

    customer_one = Customer(email="carlo@prova.it")
    customer_two = Customer(email="silvia@prova.it")
    customer_three = Customer(email="marco@prova.it")
    session.add_all([customer_one, customer_two, customer_three])
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('event')
    op.drop_table('customer')
    # ### end Alembic commands ###
